---
#
# Ansible managed
#
repository:
  description: Install eclipse and plugins on your system.
  homepage: https://buluma.github.io/
  topics: eclipse, development, ansible, molecule, tox, playbook
