---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
    - eclipse_install_path: /opt/eclipse-{{ eclipse_release }}
      eclipse_release: 2024‑06
      role: buluma.eclipse
